const RentalsLocation = [
  {
    value: "ABQ CUT",
    label: "Albuquerque (ABQ)",
    name: "Go Rentals Albuquerque",
    description: "",
    address: "2502 Clark Carr Loop SE",
    airportCode: "ABQ",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "5054774025",
      email: "ABQ@gorentals.com",
    },
  },
  {
    value: "ADS ATL",
    label: "Addison (ADS)",
    name: "Go Rentals Addison",
    description: "Atlantic",
    address: "4300 Westgrove Drive",
    airportCode: "ADS",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "9725213567",
      email: "ADS@gorentals.com",
    },
  },
  {
    value: "APA",
    label: "Englewood (APA)",
    name: "Go Rentals Denver",
    description: "Centennial Denver Jet Center",
    address: "7625 S. Peoria Street",
    airportCode: "APA",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "3038007731",
      email: "APA@gorentals.com",
    },
  },
  {
    value: "APA DJC",
    label: "Englewood (APA)",
    name: "Go Rentals Denver",
    description: "Centennial Denver Jet Center",
    address: "7625 S. Peoria Street",
    airportCode: "APA",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "3038007731",
      email: "APA@gorentals.com",
    },
  },
  {
    value: "APAN SIG",
    label: "Englewood (APA)",
    name: "Go Rentals APA North",
    description: "Signature Aviation",
    address: "7425 S. Peoria Circle",
    airportCode: "APA",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "3038007731",
      email: "APA@gorentals.com",
    },
  },
  {
    value: "APAS SIG",
    label: "Englewood (APA)",
    name: "Go Rentals APA South",
    description: "Signature Aviation",
    address: "8001 S Interport Blvd",
    airportCode: "APA",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "3038007731",
      email: "APA@gorentals.com",
    },
  },
  {
    value: "APC NAPA",
    label: "Napa (APC)",
    name: "Go Rentals Napa",
    description: "",
    address: "2030 Airport Rd.",
    airportCode: "APC",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "7078199393",
      email: "APC@gorentals.com",
    },
  },
  {
    value: "APF NAV",
    label: "Naples (APF)",
    name: "Go Rentals Naples",
    description: "Naples Municipal Airport",
    address: "160 Aviation Dr N",
    airportCode: "APF",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "2396743400",
      email: "APF@gorentals.com",
    },
  },
  {
    value: "ASE ATL",
    label: "Aspen (ASE)",
    name: "Go Rentals Aspen",
    description: "Atlantic Aviation",
    address: "300 Aspen Airport Business Cir",
    airportCode: "ASE",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "9709200226",
      email: "ase@gorentals.com",
    },
  },
  {
    value: "ATL SIG",
    label: "Atlanta (ATL)",
    name: "Go Rentals ATL",
    description: "Signature Aviation",
    address: "1200 Toffie Terrace",
    airportCode: "ATL",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "4044706800",
      email: "ATL@gorentals.com",
    },
  },
  {
    value: "Atlantic A",
    label: "Newport Beach (Corporate)",
    name: "Go Rentals Corporate",
    description: "Corporate",
    address: "4300 Campus Drive",
    airportCode: "Corporate",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "9492221900",
      email: "",
    },
  },
  {
    value: "AUS ATL",
    label: "Austin (AUS)",
    name: "Go Rentals Austin",
    description: "Atlantic Aviation",
    address: "4309 Emma Browning Ave.",
    airportCode: "AUS",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "5127688583",
      email: "AUS@gorentals.com",
    },
  },
  {
    value: "AUS SIG",
    label: "Austin (AUS)",
    name: "Go Rentals AUS",
    description: "Signature Aviation",
    address: "4321 Emma Browning Avenue",
    airportCode: "AUS",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "7376774591",
      email: "AUS@gorentals.com",
    },
  },
  {
    value: "AVL SIG",
    label: "Fletcher (AVL)",
    name: "Go Rentals AVL",
    description: "Signature Aviation",
    address: "40 Lindbergh Ln",
    airportCode: "AVL",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "2524012373",
      email: "AVL@gorentals.com",
    },
  },
  {
    value: "BCT ATL",
    label: "Boca Raton (BCT)",
    name: "Go Rentals Boca Raton",
    description: "Atlantic Aviation",
    address: "3700 Airport Road",
    airportCode: "BCT",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "5612575400",
      email: "BCT@gorentals.com",
    },
  },
  {
    value: "BCT SIG",
    label: "Boca Raton (BCT)",
    name: "Go Rentals Boca Raton",
    description: "Signature Aviation",
    address: "3300 Airport Road",
    airportCode: "BCT",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "5618949716",
      email: "BCT@gorentals.com",
    },
  },
  {
    value: "BDL ATL",
    label: "Windsor Locks (BDL)",
    name: "Go Rentals Windsor Locks",
    description: "Atlantic Aviation",
    address: "Executive Terminal Bldg 85-205",
    airportCode: "BDL",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "8607824741",
      email: "BDL@gorentals.com",
    },
  },
  {
    value: "BDL SIG",
    label: "East Granby (BDL)",
    name: "Go Rentals BDL",
    description: "Signature Aviation",
    address: "100 Signature Way",
    airportCode: "BDL",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "8606002707",
      email: "BDL@gorentals.com",
    },
  },
  {
    value: "BED ATL",
    label: "Bedford (BED)",
    name: "Go Rentals Bedford",
    description: "",
    address: "380 Hanscom Drive",
    airportCode: "BED",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "7816763980",
      email: "BED@gorentals.com",
    },
  },
  {
    value: "BED SIG",
    label: "Bedford (BED)",
    name: "Go Rentals BED",
    description: "Signature Aviation",
    address: "180 Hanscom Drive",
    airportCode: "BED",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "7814014138",
      email: "BED@gorentals.com",
    },
  },
  {
    value: "BFI",
    label: "Seattle (BFI)",
    name: "Go Rentals Seattle",
    description: "Kenmore",
    address: "8555 Perimeter Rd. S.",
    airportCode: "BFI",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "2065022424",
      email: "BFI@gorentals.com",
    },
  },
  {
    value: "BFI SIG",
    label: "Seattle (BFI)",
    name: "Go Rentals BFI",
    description: "Signature Aviation",
    address: "7149 Perimeter Road",
    airportCode: "BFI",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "2067463702",
      email: "BFI@gorentals.com",
    },
  },
  {
    value: "BFI SKY",
    label: "Seattle (BFI)",
    name: "Go Rentals Seattle",
    description: "Kenmore",
    address: "8555 Perimeter Rd. S.",
    airportCode: "BFI",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "2065022424",
      email: "BFI@gorentals.com",
    },
  },
  {
    value: "BILT PHX",
    label: "Phoenix (PHX)",
    name: "Go Rentals Arizona Biltmore",
    description: "Arizona Biltmore",
    address: "2400 East Missouri Ave.",
    airportCode: "PHX",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "4803004883",
      email: "phx@gorentals.com",
    },
  },
  {
    value: "BJC JSX",
    label: "Broomfield (BJC)",
    name: "Go Rentals Broomfield",
    description: "Broomfield",
    address: "11705 Airport Way",
    airportCode: "BJC",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "7206132222",
      email: "BJC@gorentals.com",
    },
  },
  {
    value: "BJC SIG",
    label: "Broomfield (BJC)",
    name: "Go Rentals BJC",
    description: "Signature Aviation",
    address: "11705 Airport Way",
    airportCode: "BJC",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "3039708311",
      email: "BJC@gorentals.com",
    },
  },
  {
    value: "BJCLM",
    label: "Broomfield (BJC)",
    name: "Go Rentals Broomfield",
    description: "Broomfield",
    address: "11705 Airport Way",
    airportCode: "BJC",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "7206132222",
      email: "BJC@gorentals.com",
    },
  },
  {
    value: "BNA ATL",
    label: "Nashville (BNA)",
    name: "Go Rentals",
    description: "Atlantic Aviation",
    address: "635 Hangar ave",
    airportCode: "BNA",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "6155278867",
      email: "bna@gorentals.com",
    },
  },
  {
    value: "BNA SIG",
    label: "Nashville (BNA)",
    name: "Go Rentals BNA",
    description: "Signature Aviation",
    address: "767 Hangar Lane",
    airportCode: "BNA",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "6155359461",
      email: "bna@gorentals.com",
    },
  },
  {
    value: "BOI JJC",
    label: "Boise (BOI)",
    name: "Go Rentals Boise",
    description: "Jackson Jet Center",
    address: "3815 Rickenbacker St",
    airportCode: "BOI",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "2083158022",
      email: "BOI@gorentals.com",
    },
  },
  {
    value: "BOS SIG",
    label: "Bedford (BOS)",
    name: "Go Rentals BOS",
    description: "Signature Aviation",
    address: "180 Hanscom Drive",
    airportCode: "BOS",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "6176937583",
      email: "BOS@gorentals.com",
    },
  },
  {
    value: "BUR ATL",
    label: "Burbank (BUR)",
    name: "Go Rentals Burbank",
    description: "JSX",
    address: "10750 Sherman Way",
    airportCode: "BUR",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "8182372463",
      email: "BUR@gorentals.com",
    },
  },
  {
    value: "BWI SIG",
    label: "Baltimore (BWI)",
    name: "Go Rentals BWI",
    description: "Signature Aviation",
    address: "7015 Aaronson Drive",
    airportCode: "BWI",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "4104035071",
      email: "BWI@GoRentals.com",
    },
  },
  {
    value: "BZN JET",
    label: "Belgrade (BZN)",
    name: "Go Rentals Bozeman",
    description: "",
    address: "530 Wingsway",
    airportCode: "BZN",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "4065593800",
      email: "BZN@gorentals.com",
    },
  },
  {
    value: "BZN SIG",
    label: "Belgrade (BZN)",
    name: "Go Rentals BZN",
    description: "Signature Aviation",
    address: "456 Wings Way",
    airportCode: "BZN",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "4062961842",
      email: "BZN@gorentals.com",
    },
  },
  {
    value: "CCR",
    label: "Concord (CCR)",
    name: "Go Rentals Concord",
    description: "JSX",
    address: "181 John Glenn Dr",
    airportCode: "CCR",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "9253296404",
      email: "CCR@gorentals.com",
    },
  },
  {
    value: "CHS",
    label: "Charleston (CHS)",
    name: "Go Rentals North Charleston",
    description: "Atlantic Aviation",
    address: "6060 S Aviation Ave",
    airportCode: "CHS",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "8434597997",
      email: "CHS@gorentals.com",
    },
  },
  {
    value: "CHS ATL",
    label: "Charleston (CHS)",
    name: "Go Rentals North Charleston",
    description: "Atlantic Aviation",
    address: "6060 S Aviation Ave",
    airportCode: "CHS",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "8434597997",
      email: "CHS@gorentals.com",
    },
  },
  {
    value: "CHS SIG",
    label: "Charleston (CHS)",
    name: "Go Rentals CHS",
    description: "Signature Aviation",
    address: "5875 South Aviation Avenue",
    airportCode: "CHS",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "8433768745",
      email: "CHS@gorentals.com",
    },
  },
  {
    value: "CLT WIL",
    label: "Charlotte (CLT)",
    name: "Go Rentals Charlotte",
    description: "Wilson Air",
    address: "5400 Airport Dr.",
    airportCode: "CLT",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "7044862014",
      email: "CLT@gorentals.com",
    },
  },
  {
    value: "CMA AIR",
    label: "Camarillo (CMA)",
    name: "Go Rentals Camarillo",
    description: "Camarillo",
    address: "575 Aviation Dr",
    airportCode: "CMA",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "8053225535",
      email: "CMA@gorentals.com",
    },
  },
  {
    value: "COE STA",
    label: "Hayden (COE)",
    name: "Go Rentals Coeur dAlene",
    description: "Stancraft Jet Center",
    address: "3300 Aviation Highway",
    airportCode: "COE",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "2083158020",
      email: "COE@gorentals.com",
    },
  },
  {
    value: "Corporate",
    label: "Newport Beach (Corporate)",
    name: "Go Rentals",
    description: "Corporate",
    address: "4300 Campus Drive",
    airportCode: "Corporate",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "9492221900",
      email: "kame@@gorentals.com",
    },
  },
  {
    value: "COS",
    label: "Colorado Springs (COS)",
    name: "Go Rentals Colorado Springs",
    description: "",
    address: "5763 Camber View",
    airportCode: "COS",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "7197417223",
      email: "COS@gorentals.com",
    },
  },
  {
    value: "COS CUT",
    label: "Colorado Springs (COS)",
    name: "Go Rentals Colorado Springs",
    description: "",
    address: "5763 Camber View",
    airportCode: "COS",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "7197417223",
      email: "COS@gorentals.com",
    },
  },
  {
    value: "CRQ",
    label: "Carlsbad (CRQ)",
    name: "Go Rentals - Carlsbad",
    description: "Atlantic Aviation",
    address: "2100 Palomar Airport Rd",
    airportCode: "CRQ",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "7607959955",
      email: "CRQ@gorentals.com",
    },
  },
  {
    value: "CRQ ATL",
    label: "Carlsbad (CRQ)",
    name: "Go Rentals - Carlsbad",
    description: "Atlantic Aviation",
    address: "2100 Palomar Airport Rd",
    airportCode: "CRQ",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "7607959955",
      email: "CRQ@gorentals.com",
    },
  },
  {
    value: "DAL BJC",
    label: "Dallas (DAL)",
    name: "Go Rentals Dallas",
    description: "Business Jet Center",
    address: "8611 Lemmon Ave",
    airportCode: "DAL",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "2146461324",
      email: "DAL@gorentals.com",
    },
  },
  {
    value: "DALS1 SIG",
    label: "Dallas (DAL)",
    name: "Go Rentals DAL",
    description: "Signature Aviation",
    address: "8001 Lemmon Avenue",
    airportCode: "DAL",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "2149105570",
      email: "DAL@gorentals.com",
    },
  },
  {
    value: "DALS4 SIG",
    label: "Dallas (DAL)",
    name: "Go Rentals DAL",
    description: "Signature Aviation",
    address: "7701 Lemmon Avenue",
    airportCode: "DAL",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "2146461324",
      email: "DAL@gorentals.com",
    },
  },
  {
    value: "DEN SIG",
    label: "Denver (DEN)",
    name: "Go Rentals DEN",
    description: "Signature Aviation",
    address: "7850 Harry B. Combs Parkway",
    airportCode: "DEN",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "3039708314",
      email: "DEN@gorentals.com",
    },
  },
  {
    value: "DTS ATL",
    label: "Destin (DTS)",
    name: "Go Rentals Destin",
    description: "Destin Jet",
    address: "1001 Airport Rd",
    airportCode: "DTS",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "8504609602",
      email: "DTS@gorentals.com",
    },
  },
  {
    value: "DVT",
    label: "Phoenix (DVT)",
    name: "Go Rentals Deer Valley",
    description: "Cutter Aviation",
    address: "732 W Deer Valley Rd",
    airportCode: "DVT",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "6232390228",
      email: "DVT@gorentals.com",
    },
  },
  {
    value: "ECP SSA",
    label: "Panama City (ECP)",
    name: "Go Rentals Panama City",
    description: "Southern Sky Aviation",
    address: "6300 W Bay Pkwy",
    airportCode: "ECP",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "",
      email: "ECP@gorentals.com",
    },
  },
  {
    value: "EDC",
    label: "Pflugerville (EDC)",
    name: "Go Rentals Austin Exceutive",
    description: "Henriksen Jet Center",
    address: "6012 Aviation Dr.",
    airportCode: "EDC",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "5123597894",
      email: "AUS@gorentals.com",
    },
  },
  {
    value: "EDC EXE",
    label: "Pflugerville (EDC)",
    name: "Go Rentals Austin Exceutive",
    description: "Henriksen Jet Center",
    address: "6012 Aviation Dr.",
    airportCode: "EDC",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "5123597894",
      email: "AUS@gorentals.com",
    },
  },
  {
    value: "EFD SIG",
    label: "Houston (EFD)",
    name: "Go Rentals EFD",
    description: "Signature Aviation",
    address: "11811 North Brantly Avenue #50",
    airportCode: "EFD",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "2818054666",
      email: "EFD@gorentals.com",
    },
  },
  {
    value: "EGE SIG",
    label: "Gypsum (EGE)",
    name: "Go Rentals Vail",
    description: "Signature Aviation",
    address: "871 Cooley Mesa Road",
    airportCode: "EGE",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "9703419728",
      email: "EGE@gorentals.com",
    },
  },
  {
    value: "FL Fleet",
    label: "Fort Lauderdale (FXE)",
    name: "Go Rentals Florida Fleet",
    description: "Florida Fleet",
    address: "5360 NW 20th Terrace",
    airportCode: "FXE",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "9548704500",
      email: "FXE@gorentals.com",
    },
  },
  {
    value: "FLL NAT",
    label: "Fort Lauderdale (FLL)",
    name: "Go Rentals FortLauderdale",
    description: "National Jet",
    address: "3495 SW 9th Ave.",
    airportCode: "FLL",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "9549518005",
      email: "FLL@gorentals.com",
    },
  },
  {
    value: "FLL SIG",
    label: "Fort Lauderdale (FLL)",
    name: "Go Rentals FLL",
    description: "Signature Aviation",
    address: "4050 S.W. 11th Terrace",
    airportCode: "FLL",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "9703419728",
      email: "FLL@gorentals.com",
    },
  },
  {
    value: "FMY",
    label: "Fort Myers (FMY)",
    name: "Go Rentals Fort Myers",
    description: "Page Field Airport",
    address: "5200 Captain Channing Page Dr",
    airportCode: "FMY",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "2393240121",
      email: "FMY@gorentals.com",
    },
  },
  {
    value: "FMY PAG",
    label: "Fort Myers (FMY)",
    name: "Go Rentals Fort Myers",
    description: "Page Field Airport",
    address: "5200 Captain Channing Page Dr",
    airportCode: "FMY",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "2393240121",
      email: "FMY@gorentals.com",
    },
  },
  {
    value: "FNL JET",
    label: "Loveland (FNL)",
    name: "Go Rentals Loveland",
    description: "Colorado Jet Center",
    address: "4824 Earhart Road",
    airportCode: "FNL",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "",
      email: "FNL@gorentals.com",
    },
  },
  {
    value: "FRG",
    label: "Farmingdale (FRG)",
    name: "Go Rentals Farmingdale",
    description: "Republic Jet Center",
    address: "7110 Republic Airport",
    airportCode: "FRG",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "6319204747",
      email: "FRG@gorentals.com",
    },
  },
  {
    value: "FRG REP",
    label: "Farmingdale (FRG)",
    name: "Go Rentals Farmingdale",
    description: "Republic Jet Center",
    address: "7110 Republic Airport",
    airportCode: "FRG",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "6319204747",
      email: "FRG@gorentals.com",
    },
  },
  {
    value: "FTW TEX",
    label: "Fort Worth (FTW)",
    name: "Go Rentals Fort Worth",
    description: "Texas Jet",
    address: "200 Texas Way",
    airportCode: "FTW",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "8177834100",
      email: "FTW@gorentals.com",
    },
  },
  {
    value: "FTY HIL",
    label: "Atlanta (FTY)",
    name: "Go Rentals Atlanta - FTY",
    description: "Hill Aircraft",
    address: "3948 Aviation Circle",
    airportCode: "FTY",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "4045951028",
      email: "FTY@gorentals.com",
    },
  },
  {
    value: "FTY SIG",
    label: "Atlanta (FTY)",
    name: "Go Rentals FTY",
    description: "Signature Aviation",
    address: "3956 Aviation Circle NW",
    airportCode: "FTY",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "4044706700",
      email: "FTY@gorentals.com",
    },
  },
  {
    value: "FXE BAN",
    label: "Fort Lauderdale (FXE)",
    name: "Go Rentals FortLauderdale Exec",
    description: "Banyan Air Service",
    address: "5360 NW 20th Terrace",
    airportCode: "FXE",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "9548704500",
      email: "FXE@gorentals.com",
    },
  },
  {
    value: "GEG SIG",
    label: "Spokane (GEG)",
    name: "Go Rentals GEG",
    description: "Signature Aviation",
    address: "8136 West Pilot Drive",
    airportCode: "GEG",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "5092104425",
      email: "GEG@gorentals.com",
    },
  },
  {
    value: "GSO SIG",
    label: "Greensboro (GSO)",
    name: "Go Rentals GSO",
    description: "Signature Aviation",
    address: "1060 PTI Drive",
    airportCode: "GSO",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "3365682924",
      email: "GSO@gorentals.com",
    },
  },
  {
    value: "GTU",
    label: "Georgetown (GTU)",
    name: "Go Rentals Georgetown",
    description: "Cutter",
    address: "600 S Hangar Dr",
    airportCode: "GTU",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "5126162721",
      email: "GTU@gorentals.com",
    },
  },
  {
    value: "HCR OK3",
    label: "Heber City (HCR)",
    name: "Go Rentals Heber City",
    description: "OK3 Air",
    address: "1980 Airport Rd",
    airportCode: "HCR",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "4353154241",
      email: "HCR@gorentals.com",
    },
  },
  {
    value: "HHR HMA",
    label: "Hawthorne (HHR)",
    name: "Go Rentals Hawthorne",
    description: "Hawthorne Municipal Airport",
    address: "12101 Crenshaw Blvd",
    airportCode: "HHR",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "3104090466",
      email: "HHR@gorentals.com",
    },
  },
  {
    value: "HND",
    label: "Henderson (HND)",
    name: "Go Rentals Henderson",
    description: "",
    address: "3500 Executive Terminal Drive",
    airportCode: "HND",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "7027026250",
      email: "HND@gorentals.com",
    },
  },
  {
    value: "HNL",
    label: "Honolulu (HNL)",
    name: "Go Rentals Honolulu",
    description: "",
    address: "95 Nakola Place",
    airportCode: "HNL",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "8084826319",
      email: "HNL@gorentals.com",
    },
  },
  {
    value: "HNL ATL",
    label: "Honolulu (HNL)",
    name: "Go Rentals Honolulu",
    description: "",
    address: "95 Nakola Place",
    airportCode: "HNL",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "8084826319",
      email: "HNL@gorentals.com",
    },
  },
  {
    value: "HNL SIG",
    label: "Honolulu (HNL)",
    name: "Go Rentals HNL",
    description: "Signature Aviation",
    address: "98 Kapalulu Place",
    airportCode: "HNL",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "8086465249",
      email: "HNL@gorentals.com",
    },
  },
  {
    value: "HOU ATL",
    label: "Houston (HOU)",
    name: "Go Rentals Houston",
    description: "Atlantic Aviation",
    address: "7930 Airport Boulevard",
    airportCode: "HOU",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "7136091100",
      email: "HOU@gorentals.com",
    },
  },
  {
    value: "HOU SIG",
    label: "Houston (HOU)",
    name: "Go Rentals HOU",
    description: "Signature Aviation",
    address: "7930 Airport Boulevard",
    airportCode: "HOU",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "7137690715",
      email: "HOU@gorentals.com",
    },
  },
  {
    value: "HPN",
    label: "White Plains (HPN)",
    name: "Go Rentals White Plains",
    description: "Ross Aviation",
    address: "184 Airport Road",
    airportCode: "HPN",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "9148670156",
      email: "HPN@gorentals.com",
    },
  },
  {
    value: "HPN ATL",
    label: "White Plains (HPN)",
    name: "Go Rentals White Plains",
    description: "Ross Aviation",
    address: "184 Airport Road",
    airportCode: "HPN",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "9148670156",
      email: "HPN@gorentals.com",
    },
  },
  {
    value: "HPNE SIG",
    label: "White Plains (HPN)",
    name: "Go Rentals HPN East",
    description: "Signature Aviation",
    address: "2 Hangar Road",
    airportCode: "HPN",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "9142969639",
      email: "HPN@gorentals.com",
    },
  },
  {
    value: "HPNW SIG",
    label: "White Plains (HPN)",
    name: "Go Rentals HPN West",
    description: "Signature Aviation",
    address: "85 Tower Road",
    airportCode: "HPN",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "9142969640",
      email: "HPN@gorentals.com",
    },
  },
  {
    value: "HQ Fleet",
    label: "Newport Beach (FLEET)",
    name: "Go Rentals Fleet",
    description: "Fleet Department",
    address: "4320 Campus Drive",
    airportCode: "FLEET",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "9492221900",
      email: "FLEET@gorentals.com",
    },
  },
  {
    value: "HWD SIG",
    label: "Hayward (HWD)",
    name: "Go Rentals HWD",
    description: "Signature Aviation",
    address: "1 Tuskegee Airmen Drive",
    airportCode: "HWD",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "",
      email: "OAK@gorentals.com",
    },
  },
  {
    value: "HXD",
    label: "Hilton Head Island (HXD)",
    name: "Go Rentals Hilton Head",
    description: "",
    address: "32 Hunter Rd",
    airportCode: "HXD",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "8435853013",
      email: "HXD@gorentals.com",
    },
  },
  {
    value: "HXD SIG",
    label: "Hilton Head Island (HXD)",
    name: "Go Rentals HXD",
    description: "Signature Aviation",
    address: "52 Gateway Circle",
    airportCode: "HXD",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "8433768746",
      email: "HXD@gorentals.com",
    },
  },
  {
    value: "IAD",
    label: "Dulles (IAD)",
    name: "Go Rentals Washington Dulles",
    description: "Jet Aviation",
    address: "23411 Autopilot Drive",
    airportCode: "IAD",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "7037828871",
      email: "IAD@gorentals.com",
    },
  },
  {
    value: "IAD ATL",
    label: "Dulles (IAD)",
    name: "Go Rentals Washington Dulles",
    description: "Jet Aviation",
    address: "23411 Autopilot Drive",
    airportCode: "IAD",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "7037828871",
      email: "IAD@gorentals.com",
    },
  },
  {
    value: "IAD SIG",
    label: "Dulles (IAD)",
    name: "Go Rentals IAD",
    description: "Signature Aviation",
    address: "23950 Wind Sock Drive #2000",
    airportCode: "IAD",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "5714175816",
      email: "IAD@gorentals.com",
    },
  },
  {
    value: "IAH SIG",
    label: "Houston (HOU)",
    name: "Go Rentals IAH",
    description: "Signature Aviation",
    address: "17250 Chanute Road",
    airportCode: "HOU",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "7137690714",
      email: "IAH@gorentals.com",
    },
  },
  {
    value: "ILM AER",
    label: "Wilmington (ILM)",
    name: "Go Rentals Wilmington",
    description: "Aero Center",
    address: "1830 Flightline Rd",
    airportCode: "ILM",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "7044862014",
      email: "ILM@gorentals.com",
    },
  },
  {
    value: "IND SIG",
    label: "Indianapolis (IND)",
    name: "Go Rentals IND",
    description: "Signature Aviation IND",
    address: "6390 Turner Drive",
    airportCode: "IND",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "4632079000",
      email: "IND@GoRentals.com",
    },
  },
  {
    value: "ISM",
    label: "Kissimmee (ISM)",
    name: "Go Rentals Kissimmee",
    description: "Odyssey Aviation",
    address: "3950 Merlin Drive",
    airportCode: "ISM",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "4078872066",
      email: "ISM@gorentals.com",
    },
  },
  {
    value: "ISM ODY",
    label: "Kissimmee (ISM)",
    name: "Go Rentals Kissimmee",
    description: "Odyssey Aviation",
    address: "3950 Merlin Drive",
    airportCode: "ISM",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "4078872066",
      email: "ISM@gorentals.com",
    },
  },
  {
    value: "ISM SIG",
    label: "Kissimmee (ISM)",
    name: "Go Rentals ISM",
    description: "Signature Aviation",
    address: "201 Dyer Boulevard",
    airportCode: "ISM",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "4075375200",
      email: "ISM@gorentals.com",
    },
  },
  {
    value: "JAC",
    label: "Jackson (JAC)",
    name: "Go Rentals JAC",
    description: "Jackson Hole Flight Services",
    address: "1210 E Airport Rd",
    airportCode: "JAC",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "3072893031",
      email: "JAC@gorentals.com",
    },
  },
  {
    value: "JAC JHF",
    label: "Jackson (JAC)",
    name: "Go Rentals JAC",
    description: "Jackson Hole Flight Services",
    address: "1210 E Airport Rd",
    airportCode: "JAC",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "3072893031",
      email: "JAC@gorentals.com",
    },
  },
  {
    value: "JAX SIG",
    label: "Jacksonville (JAX)",
    name: "Go Rentals JAX",
    description: "Signature Aviation",
    address: "14700 Yonge Drive",
    airportCode: "JAX",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "9042439936",
      email: "JAX@gorentals.com",
    },
  },
  {
    value: "Jet Aviati",
    label: "Newport Beach (Corporate)",
    name: "Go Rentals Corporate",
    description: "Corporate",
    address: "4300 Campus Drive",
    airportCode: "Corporate",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "9492221900",
      email: "",
    },
  },
  {
    value: "JWN CON",
    label: "Nashville (JWN)",
    name: "Go Rentals Nashville",
    description: "Contour",
    address: "110 Tune Airport Dr",
    airportCode: "JWN",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "6157039210",
      email: "JWN@gorentals.com",
    },
  },
  {
    value: "JZI",
    label: "Johns Island (JZI)",
    name: "Go Rentals Charleston Exec",
    description: "Atlantic Aviation",
    address: "3050 Transatlantic Way",
    airportCode: "JZI",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "8434597990",
      email: "JZI@gorentals.com",
    },
  },
  {
    value: "JZI ATL",
    label: "Johns Island (JZI)",
    name: "Go Rentals Charleston Exec",
    description: "Atlantic Aviation",
    address: "3050 Transatlantic Way",
    airportCode: "JZI",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "8434597990",
      email: "JZI@gorentals.com",
    },
  },
  {
    value: "KOA",
    label: "Kailua-Kona (KOA)",
    name: "Go Rentals Kona",
    description: "",
    address: "73-302 U'u Street",
    airportCode: "KOA",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "8084826320",
      email: "KOA@gorentals.com",
    },
  },
  {
    value: "KOA SIG",
    label: "Kailua-Kona (KOA)",
    name: "Go Rentals KOA",
    description: "Signature Aviation",
    address: "73-302 U'u Street",
    airportCode: "KOA",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "8086465247",
      email: "KOA@gorentals.com",
    },
  },
  {
    value: "LAL",
    label: "Lakeland (LAL)",
    name: "Go Rentals Lakeland",
    description: "Sheltair Aviation",
    address: "3440 Airfield Dr W",
    airportCode: "LAL",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "8632752384",
      email: "LAL@gorentals.com",
    },
  },
  {
    value: "LAS ATL",
    label: "Las Vegas (LAS)",
    name: "Go Rentals Las Vegas",
    description: "Atlantic Aviation",
    address: "275 E. Tropicana Ave.",
    airportCode: "LAS",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "7022626214",
      email: "LAS@gorentals.com",
    },
  },
  {
    value: "LAS SIG",
    label: "Las Vegas (LAS)",
    name: "Go Rentals LAS",
    description: "Signature Aviation",
    address: "6005 Las Vegas Boulevard",
    airportCode: "LAS",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "7029910142",
      email: "LAS@gorentals.com",
    },
  },
  {
    value: "LAX SIG",
    label: "Los Angeles (LAX)",
    name: "Go Rentals LAX",
    description: "Signature Aviation",
    address: "6201 West Imperial Highway",
    airportCode: "LAX",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "2135613608",
      email: "LAX@gorentals.com",
    },
  },
  {
    value: "LEX SIG",
    label: "Lexington (LEX)",
    name: "Go Rentals Lexington",
    description: "Signature Flight Support LEX",
    address: "4308 Hangar Drive",
    airportCode: "LEX",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "8592518523",
      email: "LEX@gorentals.com",
    },
  },
  {
    value: "LEXTAC",
    label: "Lexington (LEX)",
    name: "Go Rentals Lexington",
    description: "Signature Flight Support LEX",
    address: "4308 Hangar Drive",
    airportCode: "LEX",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "8592518523",
      email: "LEX@gorentals.com",
    },
  },
  {
    value: "LGB ATL",
    label: "Long Beach (LGB)",
    name: "Go Rentals Long Beach",
    description: "Atlantic Aviation",
    address: "3250 Airflite Way",
    airportCode: "LGB",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "5622802955",
      email: "LGB@gorentals.com",
    },
  },
  {
    value: "LGB SIG",
    label: "Long Beach (LGB)",
    name: "Go Rentals LGB",
    description: "Signature Aviation",
    address: "3333 East Spring Street #205",
    airportCode: "LGB",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "5625131370",
      email: "LGB@gorentals.com",
    },
  },
  {
    value: "LIH",
    label: "Lihue (LIH)",
    name: "Go Rentals Kauai",
    description: "",
    address: "3264 Moa'E Street",
    airportCode: "LIH",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "8087554148",
      email: "LIH@gorentals.com",
    },
  },
  {
    value: "LIH ATL",
    label: "Lihue (LIH)",
    name: "Go Rentals Kauai",
    description: "",
    address: "3264 Moa'E Street",
    airportCode: "LIH",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "8087554148",
      email: "LIH@gorentals.com",
    },
  },
  {
    value: "LIH SIG",
    label: "Lihue (LIH)",
    name: "Go Rentals LIH",
    description: "Signature Aviation",
    address: "3745 Ahukini Road #101",
    airportCode: "LIH",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "8086465248",
      email: "LIH@gorentals.com",
    },
  },
  {
    value: "MCO SIG",
    label: "Orlando (MCO)",
    name: "Go Rentals MCO",
    description: "Signature Aviation",
    address: "4215 Lindy Circle",
    airportCode: "MCO",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "4075374888",
      email: "MCO@gorentals.com",
    },
  },
  {
    value: "MDW SIG",
    label: "Chicago (MDW)",
    name: "Go Rentals MDW",
    description: "Signature Aviation",
    address: "5821 S. Central Avenue",
    airportCode: "MDW",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "3127480085",
      email: "MDW@gorentals.com",
    },
  },
  {
    value: "MIA SIG",
    label: "Miami (MIA)",
    name: "Go Rentals MIA",
    description: "Signature Aviation MIA",
    address: "5700 NW 36th Street",
    airportCode: "MIA",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "7868079227",
      email: "MIA@gorentals.com",
    },
  },
  {
    value: "MKC SIG",
    label: "Kansas City (MKC)",
    name: "Go Rentals MKC",
    description: "Signature Aviation MKC",
    address: "10 Richards Road",
    airportCode: "MKC",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "8163785122",
      email: "MKC@GoRentals.com",
    },
  },
  {
    value: "MMU ATL",
    label: "Morristown (MMU)",
    name: "Go Rentals Morristown",
    description: "Morristown Municipal Airport",
    address: "50 Airport Road",
    airportCode: "MMU",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "9738288400",
      email: "MMU@gorentals.com",
    },
  },
  {
    value: "MMU SIG",
    label: "Morristown (MMU)",
    name: "Go Rentals MMU",
    description: "Signature Aviation",
    address: "1 Airport Road",
    airportCode: "MMU",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "5513175118",
      email: "MMU@gorentals.com",
    },
  },
  {
    value: "MRY DEL",
    label: "Monterey (MRY)",
    name: "Go Rentals Monterey",
    description: "Del Monte Aviation",
    address: "100 Sky Park Dr.",
    airportCode: "MRY",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "8315826160",
      email: "MRY@gorentals.com",
    },
  },
  {
    value: "MRYDM",
    label: "Monterey (MRY)",
    name: "Go Rentals Monterey",
    description: "Del Monte Aviation",
    address: "100 Sky Park Dr.",
    airportCode: "MRY",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "8315826160",
      email: "MRY@gorentals.com",
    },
  },
  {
    value: "MRYJC",
    label: "Monterey (MRY)",
    name: "Go Rentals Monterey",
    description: "Monterey Jet Center",
    address: "300 Sky Park Way",
    airportCode: "MRY",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "8315826150",
      email: "MRY@gorentals.com",
    },
  },
  {
    value: "MSP SIG",
    label: "Minneapolis (MSP)",
    name: "Go Rentals MSP",
    description: "Signature Aviation",
    address: "3800 East 70th Street",
    airportCode: "MSP",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "6126141495",
      email: "msp@GoRentals.com",
    },
  },
  {
    value: "MYR",
    label: "Myrtle Beach (MYR)",
    name: "Go Rentals Myrtle Beach",
    description: "Beach Aviation Services",
    address: "1250 Airdrome Ave",
    airportCode: "MYR",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "8435853014",
      email: "MYR@gorentals.com",
    },
  },
  {
    value: "NEWPORT",
    label: "Newport Beach (NEWPORT)",
    name: "Go Rentals Newport Beach",
    description: "Newport Beach",
    address: "4320 Campus Drive",
    airportCode: "NEWPORT",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "9492221901",
      email: "NPB@gorentals.com",
    },
  },
  {
    value: "NPB",
    label: "Newport Beach (NPB)",
    name: "Go Rentals Newport Beach",
    description: "Newport Beach",
    address: "4320 Campus Drive",
    airportCode: "NPB",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "9492221901",
      email: "NPB@gorentals.com",
    },
  },
  {
    value: "NSM",
    label: " ()",
    name: "National Sales",
    description: "",
    address: "",
    airportCode: "",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "",
      email: "",
    },
  },
  {
    value: "OAK",
    label: "Oakland (OAK)",
    name: "Go Rentals Oakland",
    description: "JSX",
    address: "9351 Earhart Road",
    airportCode: "OAK",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "5104803383",
      email: "OAK@gorentals.com",
    },
  },
  {
    value: "OAK JSX",
    label: "Oakland (OAK)",
    name: "Go Rentals Oakland",
    description: "JSX",
    address: "9351 Earhart Road",
    airportCode: "OAK",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "5104803383",
      email: "OAK@gorentals.com",
    },
  },
  {
    value: "OAK SIG",
    label: "Oakland (OAK)",
    name: "Go Rentals OAK",
    description: "Signature Aviation",
    address: "8433 Earhart Road",
    airportCode: "OAK",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "5103921851",
      email: "OAK@gorentals.com",
    },
  },
  {
    value: "OGG",
    label: "Kahului (OGG)",
    name: "Go Rentals Maui",
    description: "",
    address: "220 Eehia Street",
    airportCode: "OGG",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "8087554149",
      email: "ogg@gorentals.com",
    },
  },
  {
    value: "OGG ATL",
    label: "Kahului (OGG)",
    name: "Go Rentals Maui",
    description: "",
    address: "220 Eehia Street",
    airportCode: "OGG",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "8087554149",
      email: "ogg@gorentals.com",
    },
  },
  {
    value: "OGG SIG",
    label: "Maui (OGG)",
    name: "Go Rentals OGG",
    description: "Signature Aviation",
    address: "25 Kuhea Street",
    airportCode: "OGG",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "8086465246",
      email: "ogg@gorentals.com",
    },
  },
  {
    value: "OPF ATL",
    label: "OpaLocka (OPF)",
    name: "Go Rentals OpaLocka",
    description: "Fontainebleau Aviation",
    address: "14200 NW 42nd Ave",
    airportCode: "OPF",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "3059648949",
      email: "OPF@gorentals.com",
    },
  },
  {
    value: "OPF FB",
    label: "OpaLocka (OPF)",
    name: "Go Rentals OpaLocka",
    description: "Fontainebleau",
    address: "14200 NW 42nd Ave",
    airportCode: "OPF",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "3059648949",
      email: "OPF@gorentals.com",
    },
  },
  {
    value: "OPF FBA",
    label: "OpaLocka (OPF)",
    name: "Go Rentals OpaLocka",
    description: "Fontainebleau Aviation",
    address: "14200 NW 42nd Ave",
    airportCode: "OPF",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "3059648949",
      email: "OPF@gorentals.com",
    },
  },
  {
    value: "OPF SIG",
    label: "OpaLocka (OPF)",
    name: "Go Rentals OPF",
    description: "Signature Aviation",
    address: "15001 NW 42nd Avenue",
    airportCode: "OPF",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "7868079223",
      email: "OPF@gorentals.com",
    },
  },
  {
    value: "OPFOJC",
    label: "OpaLocka (OPF)",
    name: "Go Rentals OpaLocka",
    description: "Atlantic Aviation",
    address: "15000 NW 44th Ave",
    airportCode: "OPF",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "3059648949",
      email: "OPF@gorentals.com",
    },
  },
  {
    value: "ORD SIG",
    label: "Chicago (ORD)",
    name: "Go Rentals ORD",
    description: "Signature Aviation",
    address: "825 Patton Drive Building 825",
    airportCode: "ORD",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "3127480086",
      email: "ORD@gorentals.com",
    },
  },
  {
    value: "ORF SIG",
    label: "Norfolk (ORF)",
    name: "Go Rentals ORF",
    description: "Signature Aviation",
    address: "6101 Burton Station Road",
    airportCode: "ORF",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "3127480086",
      email: "ORF@GoRentals.com",
    },
  },
  {
    value: "PAE",
    label: "Everett (PAE)",
    name: "Go Rentals Paine Field",
    description: "Propeller Aero Services",
    address: "9724 32nd Pl",
    airportCode: "PAE",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "4255402126",
      email: "PAE@gorentals.com",
    },
  },
  {
    value: "PAE PRO",
    label: "Everett (PAE)",
    name: "Go Rentals Paine Field",
    description: "Propeller Aero Services",
    address: "9724 32nd Pl",
    airportCode: "PAE",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "4255402126",
      email: "PAE@gorentals.com",
    },
  },
  {
    value: "PBI ATL",
    label: "West Palm Beach (PBI)",
    name: "Go Rentals West Palm",
    description: "Atlantic Aviation",
    address: "3800 Southern Blvd.",
    airportCode: "PBI",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "5612575500",
      email: "PBI@gorentals.com",
    },
  },
  {
    value: "PBI JET",
    label: "West Palm Beach (PBI)",
    name: "Go Rentals Wet Palm Beach",
    description: "Jet Aviation",
    address: "1515 Perimeter Rd",
    airportCode: "PBI",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "5617084742",
      email: "PBI@gorentals.com",
    },
  },
  {
    value: "PBI SIG",
    label: "West Palm Beach (PBI)",
    name: "Go Rentals PBI",
    description: "Signature Aviation",
    address: "3800 Southern Blvd.",
    airportCode: "PBI",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "5618949715",
      email: "PBI@gorentals.com",
    },
  },
  {
    value: "PDK",
    label: "Atlanta (PDK)",
    name: "Go Rentals Atlanta",
    description: "Atlantic Aviation",
    address: "2040 Airport Rd",
    airportCode: "PDK",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "7706610475",
      email: "PDK@gorentals.com",
    },
  },
  {
    value: "PDK ATL",
    label: "Atlanta (PDK)",
    name: "Go Rentals Atlanta",
    description: "Atlantic Aviation",
    address: "2040 Airport Rd",
    airportCode: "PDK",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "7706610475",
      email: "PDK@gorentals.com",
    },
  },
  {
    value: "PDK SIG",
    label: "Atlanta (PDK)",
    name: "Go Rentals PDK",
    description: "Signature Aviation",
    address: "3150 Corsair Drive",
    airportCode: "PDK",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "4044706777",
      email: "PDK@gorentals.com",
    },
  },
  {
    value: "PHOENIX",
    label: "Phoenix (PHX)",
    name: "Go Rentals Phoenix",
    description: "Swift Aviation",
    address: "2710 E Old Tower Rd",
    airportCode: "PHX",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "4803722447",
      email: "PHX@gorentals.com",
    },
  },
  {
    value: "PHORSRT",
    label: "Scottsdale (PHX)",
    name: "Go Rentals - The Phoenician",
    description: "The Phoenician Resort",
    address: "6000 E. Camelback Rd",
    airportCode: "PHX",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "4804232876",
      email: "PHX@gorentals.com",
    },
  },
  {
    value: "PHX CBIN",
    label: "Scottsdale (PHX)",
    name: "Go Rentals Camelback Inn",
    description: "JW Marriott Camelback Inn",
    address: "5402 E Lincoln Dr",
    airportCode: "PHX",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "4806907121",
      email: "PHX@gorentals.com",
    },
  },
  {
    value: "PHX JJC",
    label: "Phoenix (PHX)",
    name: "Go Rentals Phoenix",
    description: "Jackson Jet Center",
    address: "2710 E Old Tower Rd",
    airportCode: "PHX",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "4803722447",
      email: "PHX@gorentals.com",
    },
  },
  {
    value: "PIE SIG",
    label: "Clearwater (PIE)",
    name: "Go Rentals PIE",
    description: "Signature Aviation",
    address: "14525 Airport Parkway",
    airportCode: "PIE",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "7276061751",
      email: "PIE@gorentals.com",
    },
  },
  {
    value: "PSP ATL",
    label: "Palm Springs (PSP)",
    name: "Go Rentals Palm Springs",
    description: "Atlantic Aviation",
    address: "145 S. Gene Autry Trail",
    airportCode: "PSP",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "7604065166",
      email: "PSP@gorentals.com",
    },
  },
  {
    value: "PSP SIG",
    label: "Palm Springs (PSP)",
    name: "Go Rentals PSP",
    description: "Signature Aviation",
    address: "250 North El Cielo Road",
    airportCode: "PSP",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "7602866532",
      email: "PSP@gorentals.com",
    },
  },
  {
    value: "PTK",
    label: "Waterford (PTK)",
    name: "Go Rentals Pontiac",
    description: "Pentastar",
    address: "7310 Highland Rd",
    airportCode: "PTK",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "2487424689",
      email: "PTK@gorentals.com",
    },
  },
  {
    value: "PTK PEN",
    label: "Waterford (PTK)",
    name: "Go Rentals Pontiac",
    description: "Pentastar",
    address: "7310 Highland Rd",
    airportCode: "PTK",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "2487424689",
      email: "PTK@gorentals.com",
    },
  },
  {
    value: "PVU",
    label: "Provo (PVU)",
    name: "Go Rentals Provo",
    description: "Duncan Aviation",
    address: "262 South 3800 West",
    airportCode: "PVU",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "8018778414",
      email: "pvu@gorentals.com",
    },
  },
  {
    value: "PVU DUN",
    label: "Provo (PVU)",
    name: "Go Rentals Provo",
    description: "Duncan Aviation",
    address: "262 South 3800 West",
    airportCode: "PVU",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "8018778414",
      email: "pvu@gorentals.com",
    },
  },
  {
    value: "PWK",
    label: "Wheeling (PWK)",
    name: "Go Rentals Wheeling",
    description: "Hawthorne Global Aviation Serv",
    address: "1120 S Milwaukee Ave",
    airportCode: "PWK",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "2243482930",
      email: "pwk@gorentals.com",
    },
  },
  {
    value: "PWK HAW",
    label: "Wheeling (PWK)",
    name: "Go Rentals Wheeling",
    description: "Hawthorne Global Aviation Serv",
    address: "1120 S Milwaukee Ave",
    airportCode: "PWK",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "2243482930",
      email: "pwk@gorentals.com",
    },
  },
  {
    value: "PWK SIG",
    label: "Wheeling (PWK)",
    name: "Go Rentals PWK",
    description: "Signature Aviation",
    address: "1100 South Milwaukee Avenue",
    airportCode: "PWK",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "8476439823",
      email: "pwk@gorentals.com",
    },
  },
  {
    value: "PWM NOR",
    label: "Portland (PWM)",
    name: "Go Rentals Portland",
    description: "NEA (Northeast Air)",
    address: "1011 Westbrook Street",
    airportCode: "PWM",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "2072318436",
      email: "PWM@gorentals.com",
    },
  },
  {
    value: "RDU ATL",
    label: "Morrisville (RDU)",
    name: "Go Rentals RDU",
    description: "Atlantic Aviation",
    address: "1750 E International Dr",
    airportCode: "RDU",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "7044862014",
      email: "RDU@gorentals.com",
    },
  },
  {
    value: "RDU SIG",
    label: "Morrisville (RDU)",
    name: "Go Rentals RDU",
    description: "Signature Aviation",
    address: "1775 East International Drive",
    airportCode: "RDU",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "9842804409",
      email: "RDU@gorentals.com",
    },
  },
  {
    value: "RIL",
    label: "Rifle (RIL)",
    name: "Go Rentals Rifle",
    description: "Atlantic Aviation",
    address: "375 Co Rd 352",
    airportCode: "RIL",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "9707103146",
      email: "RIL@gorentals.com",
    },
  },
  {
    value: "RIL ATL",
    label: "Rifle (RIL)",
    name: "Go Rentals Rifle",
    description: "Atlantic Aviation",
    address: "375 Co Rd 352",
    airportCode: "RIL",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "9707103146",
      email: "RIL@gorentals.com",
    },
  },
  {
    value: "RNO",
    label: "Reno (RNO)",
    name: "Go Rentals Reno",
    description: "Atlantic Aviation",
    address: "485 S Rock Blvd",
    airportCode: "RNO",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "7759939750",
      email: "RNO@gorentals.com",
    },
  },
  {
    value: "RST SIG",
    label: "Rochester (RST)",
    name: "Go Rentals RST",
    description: "Signature Aviation",
    address: "7300 Brataas Dr SW",
    airportCode: "RST",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "6126141496",
      email: "RST@GoRentals.com",
    },
  },
  {
    value: "RYY HAW",
    label: "Kennesaw (RYY)",
    name: "Go Rentals Kennesaw",
    description: "Hawthorne Global Aviation",
    address: "1723 McCollum Pkwy NW",
    airportCode: "RYY",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "6783296460",
      email: "RYY@gorentals.com",
    },
  },
  {
    value: "SAA Fleet",
    label: "Saratoga ()",
    name: "S 1st St",
    description: "",
    address: "",
    airportCode: "",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "",
      email: "",
    },
  },
  {
    value: "SAF JET",
    label: "Santa Fe (SAF)",
    name: "Go Rentals Santa Fe",
    description: "Jet Center at Santa Fe",
    address: "109 Aviation Dr",
    airportCode: "SAF",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "5054471717",
      email: "SAF@gorentals.com",
    },
  },
  {
    value: "SAF JETC",
    label: "Santa Fe (SAF)",
    name: "Go Rentals Santa Fe",
    description: "Jet Center at Santa Fe",
    address: "109 Aviation Dr",
    airportCode: "SAF",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "5054471717",
      email: "SAF@gorentals.com",
    },
  },
  {
    value: "SAF SIG",
    label: "Santa Fe (SAF)",
    name: "Go Rentals SAF",
    description: "Signature Aviation",
    address: "109 Aviation Dr",
    airportCode: "SAF",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "5054471718",
      email: "SAF@gorentals.com",
    },
  },
  {
    value: "SAN",
    label: "San Diego (SAN)",
    name: "Go Rentals San Diego",
    description: "Go Rentals",
    address: "1380 Harbor Island drive",
    airportCode: "SAN",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "6193305933",
      email: "SAN@gorentals.com",
    },
  },
  {
    value: "SAN SIG",
    label: "San Diego (SAN)",
    name: "Go Rentals SAN",
    description: "Signature Aviation",
    address: "3300 Admiral Boland Way",
    airportCode: "SAN",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "6199431902",
      email: "SAN@gorentals.com",
    },
  },
  {
    value: "SAT SIG",
    label: "San Antonio (SAT)",
    name: "Go Rentals SAT",
    description: "Signature Aviation",
    address: "557 Sandau Road",
    airportCode: "SAT",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "2109398574",
      email: "SAT@gorentals.com",
    },
  },
  {
    value: "SAT SKY",
    label: "San Antonio (SAT)",
    name: "Go Rentals San Antonio",
    description: "Skyplace",
    address: "1770 Skyplace Blvd.",
    airportCode: "SAT",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "2105717624",
      email: "SAT@gorentals.com",
    },
  },
  {
    value: "SAV",
    label: "Savannah (SAV)",
    name: "Go Rentals SAV",
    description: "Sheltair",
    address: "100 Eddie Jungemann",
    airportCode: "SAV",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "",
      email: "SAV@gorentals.com",
    },
  },
  {
    value: "SAV SHE",
    label: "Savannah (SAV)",
    name: "Go Rentals SAV",
    description: "Sheltair",
    address: "100 Eddie Jungemann",
    airportCode: "SAV",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "",
      email: "SAV@gorentals.com",
    },
  },
  {
    value: "SAV SIG",
    label: "Savannah (SAV)",
    name: "Go Rentals SAV",
    description: "Signature Aviation",
    address: "1001 Davidson Drive",
    airportCode: "SAV",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "9122068085",
      email: "SAV@gorentals.com",
    },
  },
  {
    value: "SBA SIG",
    label: "Santa Barbara (SBA)",
    name: "Go Rentals SBA",
    description: "Signature Aviation",
    address: "515 Marxmiller Place",
    airportCode: "SBA",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "8058090900",
      email: "SBA@gorentals.com",
    },
  },
  {
    value: "SDL FMNT",
    label: "Scottsdale (SDL)",
    name: "Go Rentals Scottsdale",
    description: "Fairmont Scottsdale Princess",
    address: "7575 E Princess Dr",
    airportCode: "SDL",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "4808850021",
      email: "SDL@gorentals.com",
    },
  },
  {
    value: "SDL JWDR",
    label: "Phoenix (SDL)",
    name: "Go Rentals Desert Ridge",
    description: "JW Marriott Desert Ridge",
    address: "5350 East Marriott Drive",
    airportCode: "SDL",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "4808850020",
      email: "SDL@gorentals.com",
    },
  },
  {
    value: "SDL SIG",
    label: "Scottsdale (SDL)",
    name: "Go Rentals SDL",
    description: "Signature Aviation",
    address: "15290 North 78th Way",
    airportCode: "SDL",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "4808850022",
      email: "SDL@gorentals.com",
    },
  },
  {
    value: "SDLLM",
    label: "Scottsdale (SDL)",
    name: "Go Rentals Scottsdale",
    description: "Atlantic Aviation",
    address: "14600 N. Airport Drive",
    airportCode: "SDL",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "4809910117",
      email: "SDL@gorentals.com",
    },
  },
  {
    value: "SEA SIG",
    label: "Seattle (SEA)",
    name: "Go Rentals SEA",
    description: "Signature Aviation",
    address: "18291 Starling Road",
    airportCode: "SEA",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "2067463704",
      email: "SEA@gorentals.com",
    },
  },
  {
    value: "SFF AER",
    label: "Spokane (SFF)",
    name: "Go Rentals Felts Field",
    description: "Aero Center",
    address: "6095 E Rutter Ave.",
    airportCode: "SFF",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "5092594667",
      email: "SFF@gorentals.com",
    },
  },
  {
    value: "SFO SIG",
    label: "San Francisco (SFO)",
    name: "Go Rentals SFO",
    description: "Signature Aviation",
    address: "1052 North Access Road",
    airportCode: "SFO",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "6506065113",
      email: "SFO@gorentals.com",
    },
  },
  {
    value: "Signature",
    label: "Newport Beach (Corporate)",
    name: "Go Rentals Corporate",
    description: "Corporate",
    address: "4300 Campus Drive",
    airportCode: "Corporate",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "9492221900",
      email: "",
    },
  },
  {
    value: "SJC",
    label: "San Jose (SJC)",
    name: "Go Rentals San Jose",
    description: "Atlantic Aviation",
    address: " 1250 Aviation Ave",
    airportCode: "SJC",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "4086175656",
      email: "SJC@gorentals.com",
    },
  },
  {
    value: "SJC ATL",
    label: "San Jose (SJC)",
    name: "Go Rentals San Jose",
    description: "Atlantic Aviation",
    address: " 1250 Aviation Ave",
    airportCode: "SJC",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "4086175656",
      email: "SJC@gorentals.com",
    },
  },
  {
    value: "SJC SIG",
    label: "Santa Clara (SJC)",
    name: "Go Rentals SJC",
    description: "Signature Aviation",
    address: "323 Martin Avenue",
    airportCode: "SJC",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "4084932962",
      email: "SJC@gorentals.com",
    },
  },
  {
    value: "SKX TAO",
    label: "Taos Ski Valley (SKX)",
    name: "Go Rentals SKX",
    description: "",
    address: "116 Sutton Place",
    airportCode: "SKX",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "5054471717",
      email: "skx@gorentals.com",
    },
  },
  {
    value: "SLC ATL",
    label: "Salt Lake City (SLC)",
    name: "Go Rentals Salt Lake City",
    description: "Atlantic Aviation",
    address: "369 North 2370 West",
    airportCode: "SLC",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "8018939263",
      email: "SLC@gorentals.com",
    },
  },
  {
    value: "SLC SIG",
    label: "Salt Lake City (SLC)",
    name: "Go Rentals Salt Lake City",
    description: "Atlantic Aviation",
    address: "303 North 2370 W",
    airportCode: "SLC",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "8018939263",
      email: "SLC@gorentals.com",
    },
  },
  {
    value: "SMO ATL",
    label: "Santa Monica (SMO)",
    name: "Go Rentals Santa Monica",
    description: "Atlantic Aviation",
    address: "2828 Donald Douglas Loop North",
    airportCode: "SMO",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "3104961766",
      email: "SMO@gorentals.com",
    },
  },
  {
    value: "SNA",
    label: "Santa Ana (SNA)",
    name: "Go Rentals Santa Ana",
    description: "ACI Jet",
    address: "19711 Campus Drive",
    airportCode: "SNA",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "9492095030",
      email: "SNA@gorentals.com",
    },
  },
  {
    value: "SNA ACI",
    label: "Santa Ana (SNA)",
    name: "Go Rentals Santa Ana",
    description: "ACI Jet",
    address: "19301 Campus Drive",
    airportCode: "SNA",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "9495382020",
      email: "SNA@gorentals.com",
    },
  },
  {
    value: "SNA ACI S",
    label: "Santa Ana (SNA)",
    name: "Go Rentals Santa Ana",
    description: "ACI Jet",
    address: "19711 Campus Drive",
    airportCode: "SNA",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "9492095030",
      email: "SNA@gorentals.com",
    },
  },
  {
    value: "SRQ",
    label: "Sarasota (SRQ)",
    name: "Go Rentals Sarasota",
    description: "Dolphin Aviation",
    address: "8191 N Tamiami Trail",
    airportCode: "SRQ",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "9412171300",
      email: "SRQ@gorentals.com",
    },
  },
  {
    value: "SRQ ATL",
    label: "Sarasota (SRQ)",
    name: "Go Rentals Sarasota",
    description: "Rectrix Aerodrome Center",
    address: "8250 15th St E",
    airportCode: "SRQ",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "9414043830",
      email: "SRQ@gorentals.com",
    },
  },
  {
    value: "SRQ DOL",
    label: "Sarasota (SRQ)",
    name: "Go Rentals Sarasota",
    description: "Dolphin Aviation",
    address: "8191 N Tamiami Trail",
    airportCode: "SRQ",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "9412171300",
      email: "SRQ@gorentals.com",
    },
  },
  {
    value: "SRQ RAC",
    label: "Sarasota (SRQ)",
    name: "Go Rentals Sarasota",
    description: "Rectrix Aerodrome Center",
    address: "8250 15th St E",
    airportCode: "SRQ",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "9414043830",
      email: "SRQ@gorentals.com",
    },
  },
  {
    value: "SRQ SKY",
    label: "Venice ()",
    name: "Skyport Aviation - Fleet only",
    description: "",
    address: "400 Airport Ave. E",
    airportCode: "",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "941",
      email: "",
    },
  },
  {
    value: "STL SIG",
    label: "Saint Louis (STL)",
    name: "Go Rentals STL",
    description: "Signature Aviation",
    address: "5995 James S. McDonnell Blvd.",
    airportCode: "STL",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "3145566993",
      email: "STL@GoRentals.com",
    },
  },
  {
    value: "STS",
    label: "Santa Rosa (STS)",
    name: "Go Rentals Santa Rosa",
    description: " Kaiser Air",
    address: "2240 Airport Blvd",
    airportCode: "STS",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "7072067300",
      email: "STS@gorentals.com",
    },
  },
  {
    value: "SUA ATL",
    label: "Stuart (SUA)",
    name: "Go Rentals Stuart",
    description: "Atlantic Aviation",
    address: "2240 SE Witham Field Drive",
    airportCode: "SUA",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "7729198895",
      email: "SUA@gorentals.com",
    },
  },
  {
    value: "SUS SIG",
    label: "Chesterfield (SUS)",
    name: "Go Rentals SUS",
    description: "Signature Aviation",
    address: "18260 Edison Ave",
    airportCode: "SUS",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "",
      email: "SUS@GoRentals.com",
    },
  },
  {
    value: "TEB",
    label: "Teterboro (TEB)",
    name: "Go Rentals Teterboro",
    description: "Teterboro",
    address: "112 Lindbergh Dr",
    airportCode: "TEB",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "5513086688",
      email: "TEB@gorentals.com",
    },
  },
  {
    value: "TEBE SIG",
    label: "Teterboro (TEB)",
    name: "Go Rentals TEB East",
    description: "Signature Aviation",
    address: "200 Fred Wehran Drive",
    airportCode: "TEB",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "5513175115",
      email: "TEB@gorentals.com",
    },
  },
  {
    value: "TEBS SIG",
    label: "Teterboro (TEB)",
    name: "Go Rentals Teterboro",
    description: "Teterboro",
    address: "101 Charles A Lindbergh Drive",
    airportCode: "TEB",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "5513175116",
      email: "TEB@gorentals.com",
    },
  },
  {
    value: "TEBW SIG",
    label: "Teterboro (TEB)",
    name: "Go Rentals TEB WEST",
    description: "Signature Aviation",
    address: "485 Industrial Avenue",
    airportCode: "TEB",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "5513175117",
      email: "TEB@gorentals.com",
    },
  },
  {
    value: "TKI MKA",
    label: "McKinney (TKI)",
    name: "Go Rentals McKinney",
    description: "McKinney Air Center",
    address: "1500 Industrial Blvd",
    airportCode: "TKI",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "4694210284",
      email: "TKI@gorentals.com",
    },
  },
  {
    value: "TMB SIG",
    label: "Tamiami (TMB)",
    name: "Go Rentals TMB",
    description: "Signature Aviation",
    address: "14150 SW 129th Street",
    airportCode: "TMB",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "7868079232",
      email: "TMB@gorentals.com",
    },
  },
  {
    value: "TME",
    label: "Brookshire (HOU)",
    name: "Go Rentals Houston",
    description: "Henriksen Jet Center",
    address: "1900 Cardiff Rd",
    airportCode: "HOU",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "7134241054",
      email: "HOU@gorentals.com",
    },
  },
  {
    value: "TPA SHE",
    label: "Tampa (TPA)",
    name: "Go Rentals Tampa",
    description: "Sheltair Aviation",
    address: "4751 Jim Walter Blvd",
    airportCode: "TPA",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "8132124828",
      email: "TPA@gorentals.com",
    },
  },
  {
    value: "TPA SIG",
    label: "Tampa (TPA)",
    name: "Go Rentals TPA",
    description: "Signature Aviation",
    address: "2450 North Westshore Blvd",
    airportCode: "TPA",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "8134413595",
      email: "TPA@gorentals.com",
    },
  },
  {
    value: "Travel",
    label: "Hasbrouck Heights ()",
    name: "Go Rentals Travel Dep",
    description: "Go Rentals Travel Dep",
    address: "500 Route 17 South",
    airportCode: "",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "8336102019",
      email: "travelgroup@gorentals.com",
    },
  },
  {
    value: "TRK TAH",
    label: "Truckee (TRK)",
    name: "Go Rentals Truckee",
    description: "",
    address: "10266 Truckee Airport Rd",
    airportCode: "TRK",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "5303232777",
      email: "TRK@gorentals.com",
    },
  },
  {
    value: "TRM ATL",
    label: "Thermal (TRM)",
    name: "Go Rentals Thermal",
    description: "Atlantic Aviation",
    address: "86-400 Lightning Street",
    airportCode: "TRM",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "7604065166",
      email: "TRM@gorentals.com",
    },
  },
  {
    value: "TRM DJ",
    label: "Thermal (TRM)",
    name: "Go Rentals Thermal",
    description: "Desert Jet TRM",
    address: "56-600 Invader",
    airportCode: "TRM",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "7604065166",
      email: "TRM@gorentals.com",
    },
  },
  {
    value: "TYS SIG",
    label: "Alcoa (TYS)",
    name: "Go Rentals Knoxville",
    description: "SIgnature Aviation",
    address: "2343 W General Aviation Dr",
    airportCode: "TYS",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "8652055578",
      email: "tys@gorentals.com",
    },
  },
  {
    value: "UDD",
    label: "Bermuda Dunes (UDD)",
    name: "Go Rentals Bermuda Dunes",
    description: "Bermuda Dunes Executive",
    address: "79880 Ave 42",
    airportCode: "UDD",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "7608498717",
      email: "UDD@gorentals.com",
    },
  },
  {
    value: "Vail",
    label: "Vail (Vail)",
    name: "Go Rentals Four Seasons Resort",
    description: "Four Seasons Resort Vail",
    address: "1 Vail Rd",
    airportCode: "Vail",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "9703064030",
      email: "vail@gorentals.com",
    },
  },
  {
    value: "VIP",
    label: "Palm Springs ()",
    name: "Go Rentals VIP Services",
    description: "Go Rentals VIP Services",
    address: "145 S. Gene Autry Trail",
    airportCode: "",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "8888881143",
      email: "VIPSERVICES@gorentals.com",
    },
  },
  {
    value: "VNY",
    label: "Van Nuys (VNY)",
    name: "Go Rentals Van Nuys",
    description: "Van Nuys",
    address: "16644 Rosco Blvd",
    airportCode: "VNY",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "8182351455",
      email: "VNY@gorentals.com",
    },
  },
  {
    value: "VNY SIG",
    label: "Van Nuys (VNY)",
    name: "Go Rentals VNY",
    description: "Signature Aviation",
    address: "7155 Valjean Avenue",
    airportCode: "VNY",
    startTime: "00:00",
    endTime: "00:00",
    contactDetail: {
      phone: "8184633119",
      email: "VNY@gorentals.com",
    },
  },
];
